### ISSUE TITLE
Game Room Display User Story

### ISSUE THREAD

**Issue by judy0ye** [escape-link/escapelink-fe#18]
## User Story
- As a game player, after I click on the start game button, I see the escape room displayed

## Acceptance Criteria
* Scenario: A game player visits the page and clicks on the start game button*

Given that a viewer clicks on the start game button
(A link will be generated below for the game player to share?)
Bob's story and the button will not be visible and only the escape room will be visible
The viewer can click on a button to go back to see the landing page again

**Comment by Averyberryman** [comment]
done
