### ISSUE TITLE
Room 1 Preview User Story

### ISSUE THREAD

**Issue by judy0ye** [escape-link/escapelink-fe#19]
## User Story
- As a game player, I can click on 'Room 1' button to see Room 1's preview

## Acceptance Criteria
*Scenario: A game player clicks on Room 1*

Given that a game player clicks on the Room 1 button
The landing page is not visible
The preview for Room 1 is visible
A back button is visible for the game player to go back to the landing page
A start game button is visible for the game player to start a game

**Comment by Averyberryman** [comment]
Done
